### ISSUE TITLE
Unable to detect melty blood

### ISSUE THREAD

**Issue by AlxFG** [Kikasuru/melty_streaming#1]
Running the server, it is unable to detect the game and only shows the the borders being empty. The version of python I was using is 3.6.8

In cmd it keeps printing
Traceback (most recent call last):
  File "C:\Users\Alx\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Alx\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Alx\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Alx\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Alx\Desktop\tools\melty_streaming\melty_streaming\api.py", line 31, in get_state
    if ProcessHook.look_for_melty() is False:
  File "C:\Users\Alx\Desktop\tools\melty_streaming\melty_streaming\proc.py", line 41, in look_for_melty
    cls.PROCESS_ID = cls.get_pid()
  File "C:\Users\Alx\Desktop\tools\melty_streaming\melty_streaming\proc.py", line 25, in get_pid
    task_data = subprocess.check_output(cmd, creationflags=subprocess.CREATE_NO_WINDOW).decode("UTF8")
AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'
127.0.0.1 - - [17/Aug/2021 18:36:44] "GET /state HTTP/1.1" 500 -

**Comment by Kikasuru** [comment]
Seems like this problem is stemming from the way it tries to get the Melty PID, I'll go ahead and investigate this.

**Comment by Kikasuru** [comment]
[So it seems SubProcesses were changed in Python 3.7](https://docs.python.org/3.7/library/asyncio-subprocess.html), so I'm probably going to bump up the required version to 3.7.x.

**Comment by Kikasuru** [comment]
You should be fine if you install 3.7.x or higher, [3.9.6](https://www.python.org/downloads/release/python-396/) is highly recommended.

**Comment by Kikasuru** [comment]
A release has been put out that fixes this issue!

https://github.com/Kikasuru/melty_streaming/releases/tag/1.1.1
